### ISSUE TITLE
A question about the representation of virtual node tokens

### ISSUE THREAD

**Issue by Miracle-dz** [PeterGriffinJin/Edgeformers#1]
You have done an interesting job! I have a question about the code implement of node embeddings. In your paper, you have mentioned there is a mapping matrix for the node embedding of every layer. 
![screenshot20240109](https://github.com/PeterGriffinJin/Edgeformers/assets/46878562/ca39c76c-83d1-4a43-8b3b-4e6f3ff329c5)

But in your code, (Edgeformer-N/src/model/EdgeformerN.py)line 228-230:
![screenshot20240109 (1)](https://github.com/PeterGriffinJin/Edgeformers/assets/46878562/bb540349-0968-4d82-86a4-26357e498605)
Node embedding is obtained by linear mapping and is used by encoder(line246-251):
![screenshot20240109 (2)](https://github.com/PeterGriffinJin/Edgeformers/assets/46878562/188920e5-1c61-4920-9295-75718ec87ed2)

There is a loop of every layer in encoder, but "center_embedding" and "neighbor_embedding" are not updated by specific mapping matrix in every layer. It seems node embedding"Zi" maintain same in every layer. But according to the statement in your paper, there should be different mapping matrix and different node embeddings of every layer.
![screenshot20240109 (3)](https://github.com/PeterGriffinJin/Edgeformers/assets/46878562/7d4585ea-0122-48d8-8b5c-f8570575d907)

Could you please give some explanation? Thank you very much!

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you so much for the message and I'm sorry for the late reply.

Yes, you are right. In this implementation version, W^{(l)}_n is the same for all the layers. We empirically find that making W^{(l)}_n the same for all the layers and making them different have nearly the same performance. To keep the implementation as simple as possible, we use W^{(l)}_n the same for all the layers in the open-source code.

Best,
Bowen
